E.G.G. #3-2 ハンズオン追加
GoogleCloudPlatform/gcp-getting-started-lab-jp pull request #68
Opened 2021-04-28 06:48 UTC by govargo

## E.G.G. #3-2 ハンズオンを追加

 * Spanner Webアプリ: GKEハンズオンでも利用するアプリ
 * Tutorial.md: teachme用のチュートリアル
 * README.md: CloudShell へのリンク

## Spanner Webアプリ

REST APIとして起動する。
`/players` HTTP Pathに対して、GET, POST, PUT, DELETE を受けることで対応する操作をCloud Spannerに対して行う。
(例: GETでPlayersテーブルのデータを一覧表示、POSTで新規Player作成など)

2021-04-28 06:52 UTC, govargo commented
To: @shabutora 
cc. @yutako0217

2021-04-28 06:55 UTC, govargo commented
+ CC. @takabow

2021-05-07 00:14 UTC, shabutora approved these changes

2021-05-09 14:41 UTC, takabow requested changes

2021-05-09 14:41 UTC, takabow commented on gaming/egg3-2/tutorial.md
> +続いて、環境変数 `PROJECT_ID` に、各自で利用しているプロジェクトのIDを格納しておきます。以下のコマンドを、Cloud Shell のターミナルで実行してください。
We used `PROJECT_ID` as an environment variable in previous versions, but this time you seem to be using `GOOGLE_CLOUD_PROJECT` as an alternative environment variable.

I agree with using `GOOGLE_CLOUD_PROJECT`.

Could you remove L122-132 so that E.G.G. students don't get confused?

2021-05-10 01:40 UTC, govargo commented on gaming/egg3-2/tutorial.md
> +続いて、環境変数 `PROJECT_ID` に、各自で利用しているプロジェクトのIDを格納しておきます。以下のコマンドを、Cloud Shell のターミナルで実行してください。
done

2021-05-10 14:13 UTC, yutako0217 reviewed
すみません、Tutorialのコメントばっかりになってしまいました。。。

2021-05-11 01:31 UTC, govargo commented on gaming/egg3-2/tutorial.md
> +gcloud config set project <今回使う Google Cloud のプロジェクト ID>
"{{project-id}}" 知りませんでした。こちらを使うように修正しました

2021-05-11 01:32 UTC, govargo commented on gaming/egg3-2/tutorial.md
> +または
Code Snippet を分けて、それぞれ1つのコマンドになるように修正しました

2021-05-11 01:36 UTC, govargo commented on gaming/egg3-2/tutorial.md
> +VALUES ('78120943-5b8e-4049-acf3-b6e070d017ea', 2, 5);
ご認識の通りで、説明文を次のように修正しました。

-------------------------------

以下の SQL の player_id(`78120943-5b8e-4049-acf3-b6e070d017ea` の部分) を変えてから、同様に「DDLステートメント」に貼り付け、「クエリを実行」を選択してください。

2021-05-11 15:24 UTC, yutako0217 commented
本質じゃないところへのコメントすみません。
対応ありがとうございます！

`"{{project-id}}"` が入ってなさそうでしたが、とりあえずLGTMです！

2021-05-12 01:50 UTC, govargo commented
> "{{project-id}}" が入ってなさそうでしたが、とりあえずLGTMです！

`{{project-id}}` をtutorial.md に入れました。コミットをammendで上書きしたのでもしかしたら画面の更新漏れかもしれません

2021-05-12 08:42 UTC, merged